### ISSUE TITLE
Add support for prerelease releases

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-github-release#4]
![image](https://user-images.githubusercontent.com/1173057/44742032-cfbb2980-aacc-11e8-9b78-4b43c24e512e.png)
- https://developer.github.com/v3/repos/releases/#create-a-release

![image](https://user-images.githubusercontent.com/1173057/44742045-dea1dc00-aacc-11e8-9b48-042b36eee1c9.png)

**Comment by godrei** [comment]
@bootstraponline thanks for the feature request, we scheduled to implement this!

**Comment by bootstraponline** [comment]
I think PRs are always welcome. 🙂

**Comment by agap** [comment]
I was just thinking that since @godrei said they already scheduled it for implementation it makes sense for me to ask first so that I don't spend time & effort in case this is something that was already developed and just waits to be pushed and merged. :)

Otherwise I could take a look into this either during the nearest weekend or on the next week's weekend.

**Comment by godrei** [comment]
Hi @agap ,
PRs are always welcome!
We have some urgent tasks before this one.
